spring.application.name=startinvest-backend

#conexão com a base de dados
spring.datasource.url=jdbc:postgresql://localhost:5433/startinvest
spring.datasource.username=startinvest
spring.datasource.password=startinvest